### ISSUE TITLE
at least use bootstrap.bundle.min.js instead of popper.js?

### ISSUE THREAD

**Issue by xerroxcopy** [xerroxcopy/xerroxgit#3]

**Comment by xerroxcopy** [comment]
```scss
  &:hover:not(.expand) {
    border-bottom: 4px solid $primary;
    color: $primary;
  }
```
