### ISSUE TITLE
place border-bottom on hovered a:hover

### ISSUE THREAD

**Issue by xerroxcopy** [xerroxcopy/xerroxgit#6]
```scss
a {
  font-style: italic;
  color: #110c1a;
  text-decoration: none;
  &[aria-expanded='false'] {
    // default section collapse style
    // change .text-darker a&[]... too
    padding: 0 0 2px;
    border-bottom: 4px solid black;
  }
  transition: color 250ms ease;
  :hover {
    padding: 4px 4px 0 4px;
    border-bottom: 4px dashed #9d4794;
  }
}
```
but doesn't work:
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/13182777/86574246-81242380-bfb0-11ea-866e-429e0840e17b.png">
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/13182777/86574256-84b7aa80-bfb0-11ea-87d5-02dfb3c3deb0.png">

**Comment by xerroxcopy** [comment]
```scss
  &:hover:not(.expand) {
    border-bottom: 4px solid $primary;
    color: $primary;
  }
```
